[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = ["MIT", "Apache-2.0", "ISC", "BSD-3-Clause", "Unicode-3.0"]
confidence-threshold = 0.8
exceptions = [
    { name = "webpki-roots", allow = [
        "MPL-2.0",
    ] },
]

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
