targets = []

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-3-Clause"]
copyleft = "deny"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { name = "untrusted", allow = [
        "ISC",
    ] },
    { name = "ring", allow = [
        "MIT",
        "ISC",
        "OpenSSL",
    ] },
    { name = "webpki-roots", allow = [
        "MPL-2.0",
    ] },
    { name = "webpki", allow = [
        "ISC",
    ] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "encoding_rs"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [{ path = "COPYRIGHT", hash = 0x39f8ad31 }]

[bans]
multiple-versions = "deny"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
