on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.56.0"
          override: true

      - run: rustup component add rustfmt
      - run: cargo fmt -- --check --color always

      - run: rustup component add clippy
      - run: cargo fetch
      - run: cargo clippy --all-features --all-targets -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.56.0"
          override: true
      - run: cargo fetch
      - name: cargo test build
        run: cargo build --tests --all-features
      - run: cargo test --all-features

  deny-check:
    name: cargo-deny
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  publish-check:
    name: Publish Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.56.0"
          override: true
      - run: cargo fetch
      - name: cargo publish
        run: cargo publish --dry-run
